import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_contexts/CartContextProvider";
import { getUserCart } from "./_actions/cart.Action";

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by FreshCart",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userCart = await getUserCart();

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <MySessionProvider>
          <CartContextProvider userCart={userCart}>
            <Toaster />
            <Navbar />
            {children}
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}